#!/usr/bin/env python3
"""
Git Init without Git - A pure Python implementation
Initializes a directory as a Git repository without requiring Git installation.
"""

import os
import sys
from pathlib import Path


def init_git_directory(repo_path, branch='main', remote_url=None):
    """Initialize a proper .git directory structure."""
    git_dir = os.path.join(repo_path, '.git')

    # Check if already a git repository
    if os.path.exists(git_dir):
        print(f"Reinitialized existing Git repository in {git_dir}")
        return True

    # Create .git directory structure
    os.makedirs(git_dir, exist_ok=True)
    os.makedirs(os.path.join(git_dir, 'objects', 'info'), exist_ok=True)
    os.makedirs(os.path.join(git_dir, 'objects', 'pack'), exist_ok=True)
    os.makedirs(os.path.join(git_dir, 'refs', 'heads'), exist_ok=True)
    os.makedirs(os.path.join(git_dir, 'refs', 'tags'), exist_ok=True)
    os.makedirs(os.path.join(git_dir, 'info'), exist_ok=True)
    os.makedirs(os.path.join(git_dir, 'hooks'), exist_ok=True)

    # Create HEAD file pointing to the initial branch
    with open(os.path.join(git_dir, 'HEAD'), 'w') as f:
        f.write(f'ref: refs/heads/{branch}\n')

    # Create config file
    config_content = f"""[core]
\trepositoryformatversion = 0
\tfilemode = false
\tbare = false
\tlogallrefupdates = true
\tsymlinks = false
\tignorecase = true
"""
    # Add remote origin if provided
    if remote_url:
        config_content += f"""[remote "origin"]
\turl = {remote_url}
\tfetch = +refs/heads/*:refs/remotes/origin/*
[branch "{branch}"]
\tremote = origin
\tmerge = refs/heads/{branch}
"""
        # Create remotes directory for tracking
        os.makedirs(os.path.join(git_dir, 'refs', 'remotes', 'origin'), exist_ok=True)

    with open(os.path.join(git_dir, 'config'), 'w') as f:
        f.write(config_content)

    # Create description file
    with open(os.path.join(git_dir, 'description'), 'w') as f:
        f.write('Unnamed repository; edit this file to name the repository.\n')

    # Create info/exclude file (local gitignore)
    with open(os.path.join(git_dir, 'info', 'exclude'), 'w') as f:
        f.write('# git ls-files --others --exclude-from=.git/info/exclude\n')
        f.write('# Lines that start with \'#\' are comments.\n')
        f.write('# For a project mostly in C, the following would be a good set of\n')
        f.write('# temporary files generated by your text editor\n')
        f.write('# or tool to ignore.\n')
        f.write('#*.[oa]\n')
        f.write('#*~\n')

    print(f"Initialized empty Git repository in {git_dir}")
    return True


def parse_github_url(url):
    """Parse a GitHub URL and return owner and repo."""
    import re

    if not url:
        return None, None

    url = url.strip()

    # Remove .git suffix if present
    if url.endswith('.git'):
        url = url[:-4]

    # Handle GitHub URLs
    github_match = re.search(r'github\.com[/:]([^/]+)/([^/.\\s]+)', url)
    if github_match:
        return github_match.group(1), github_match.group(2)

    return None, None


def init_repository(repo_path=None, branch='main', remote_url=None):
    """Initialize a directory as a Git repository.

    Args:
        repo_path: Path to initialize. Defaults to current directory.
        branch: Initial branch name. Defaults to 'main'.
        remote_url: Optional remote origin URL to configure.

    Returns:
        True on success, False on failure.
    """
    # Default to current directory
    if repo_path is None:
        repo_path = os.getcwd()

    repo_path = os.path.abspath(repo_path)

    # Create directory if it doesn't exist
    if not os.path.exists(repo_path):
        try:
            os.makedirs(repo_path, exist_ok=True)
            print(f"Created directory: {repo_path}")
        except OSError as e:
            print(f"Error: Could not create directory '{repo_path}': {e}")
            return False

    # Verify it's a directory
    if not os.path.isdir(repo_path):
        print(f"Error: '{repo_path}' is not a directory")
        return False

    # Normalize remote URL if provided
    if remote_url:
        remote_url = remote_url.strip()
        # Ensure .git suffix for consistency
        if 'github.com' in remote_url and not remote_url.endswith('.git'):
            remote_url = remote_url + '.git'

    # Initialize the .git directory
    success = init_git_directory(repo_path, branch, remote_url)

    if success and remote_url:
        owner, repo = parse_github_url(remote_url)
        if owner and repo:
            print(f"Remote origin set to: {owner}/{repo}")

    return success


def main():
    """Main entry point."""
    import argparse

    parser = argparse.ArgumentParser(
        description='Initialize a directory as a Git repository without Git installed.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python PyGitInit.py
  python PyGitInit.py ./my-project
  python PyGitInit.py -b main
  python PyGitInit.py --remote https://github.com/owner/repo
  python PyGitInit.py ./my-project -b develop --remote https://github.com/owner/repo
"""
    )

    parser.add_argument(
        'path',
        nargs='?',
        default=None,
        help='Directory to initialize (default: current directory)'
    )

    parser.add_argument(
        '-b', '--branch',
        default='main',
        help='Initial branch name (default: main)'
    )

    parser.add_argument(
        '--remote',
        default=None,
        help='Remote origin URL to configure (optional)'
    )

    args = parser.parse_args()

    success = init_repository(args.path, args.branch, args.remote)
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
