#!/usr/bin/python3
#---------------------ffmpeg-write-tags-from-csv.py v0.01--------------------------
# This code writes BWF tags to all MP3 files listed in a CSV file
# generated by HST website.  
# The first row of the downloaded CSV [headers] must be edited to
# match the BWF labels used below.  e.g ICOP, ISRC, ICRD, ISBJ, ICMT, INAM, IPRD
# 
# Created Sat 24 Feb 2024 21:15:20 PM CST by JAU - Writes one file at a time

# TODO read CSV data and loop thru files listed in CSV file extracting metadata 
# and writing tags for each file; add MP# version
# reuse write-tags-from-csv.py v0.66 as much as possible
#
# **********Updated Mon 26 Jun 2023 12:30:58 PM CDT  Added error trap for missing TIFFs from CSV files **************

#----------------------------------------------------------------

import subprocess

# Path to your input MP3 file
input_mp3_file = "SR59-12 BlackHawkWaltz.mp3"

# Metadata dictionary with ID3 tag keys
metadata = {
    'TIT1': 'TIT1: Title - HST playing pinano',
    'TIT2': 'TIT2: Title - HST playing the Black Hawk Watz',
    'TIT3': 'TIT3: Title - HST playing the Black Hawk Watz in the White House',
    'TPE1': 'TPEI: Artist - Harry Truman',
    'TALB': 'TALB: Album ',
    'TYER': 'TYER: Year 1948',
    'TDAT': 'TDAT: September 30, 1948',
    'TCOP': 'TCOP: Copyright - Restricted',
    'TCMT': 'TCMT: Comment - HST playing piano', 
    'TOWN': 'TOWN: Owner - Harry S. Truman Presidental Library',  
    # Add more ID3 tag fields as needed
}

# Constructing the ffmpeg command for MP3 with ID3 tags
ffmpeg_command = [
    'ffmpeg',
    '-i', input_mp3_file,
]

# Add ID3 tag fields to the ffmpeg command
for key, value in metadata.items():
    ffmpeg_command.extend(['-metadata', f'{key}={value}'])

# Specify ID3v2.3 version for MP3 files
ffmpeg_command.extend(['-id3v2_version', '3'])

# Output MP3 file path
output_mp3_file = "output.mp3"

# Add output file path to the ffmpeg command
ffmpeg_command.append(output_mp3_file)

# Execute the ffmpeg command to embed ID3 tags into the MP3 file
subprocess.run(ffmpeg_command)

