#!/usr/bin/python3
#---------------------ffmpeg-write-tags-from-csv.py v0.01--------------------------
# This code writes BWF tags to all WAV files listed in a CSV file
# generated by HST website.  
# The first row of the downloaded CSV [headers] must be edited to
# match the BWF labels used below.  e.g ICOP, ISRC, ICRD, ISBJ, ICMT, INAM, IPRD
# 
# Created Sat 24 Feb 2024 21:15:20 PM CST by JAU - Writes one file at a time

# TODO read CSV data and loop thru files listed in CSV file extracting metadata 
# and writing tags for each file; add MP# version
# reuse write-tags-from-csv.py v0.66 as much as possible
#
# **********Updated Mon 26 Jun 2023 12:30:58 PM CDT  Added error trap for missing TIFFs from CSV files **************

#----------------------------------------------------------------

import subprocess

# Path to your input WAV file
input_wav_file = "input.wav"

# Metadata dictionary
metadata = {
    'ISBJ': 'Subject',
    'IPRD': 'Name i.e. Accession Number',
    'INAM': 'Title',
    'ICOP': 'Copyright',
    'ICMT': 'Comment',
    'ISRC': 'Source: Harry S. Truman Library',
    'ICRD': 'Date: Septemer 30, 1948',
    # Add more metadata fields as needed
}

# Constructing the ffmpeg command
ffmpeg_command = [
    'ffmpeg',
    '-i', input_wav_file,
]

# Add metadata fields to the ffmpeg command
for key, value in metadata.items():
    ffmpeg_command.extend(['-metadata', f'{key}={value}'])

# Output WAV file path
output_wav_file = "output.wav"

# Add output file path to the ffmpeg command
ffmpeg_command.append(output_wav_file)

# Execute the ffmpeg command
subprocess.run(ffmpeg_command)

