"""
Generate version_info.txt for PyInstaller from __init__.py.

Run before building:
    python generate_version_info.py

Output: version_info.txt (referenced by HPM.spec EXE version= parameter)
"""

import re
from pathlib import Path

# Read version from __init__.py
init_text = Path("__init__.py").read_text(encoding="utf-8")
version_str = re.search(r'__version__\s*=\s*"([^"]+)"', init_text).group(1)
author = re.search(r'__author__\s*=\s*"([^"]+)"', init_text).group(1)

# Parse version into 4-tuple, padding with zeros
parts = [int(x) for x in version_str.split(".")]
while len(parts) < 4:
    parts.append(0)
v = tuple(parts)

year = "2026"
copyright_str = f"Copyright (c) {year} {author}"

content = f"""\
# Generated by generate_version_info.py — do not edit by hand.
# Rebuild with: python generate_version_info.py
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={v},
    prodvers={v},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'{author}'),
         StringStruct(u'FileDescription', u'HSTL Photo Metadata'),
         StringStruct(u'FileVersion', u'{version_str}'),
         StringStruct(u'InternalName', u'HPM'),
         StringStruct(u'LegalCopyright', u'{copyright_str}'),
         StringStruct(u'OriginalFilename', u'HPM.exe'),
         StringStruct(u'ProductName', u'HSTL Photo Metadata (HPM)'),
         StringStruct(u'ProductVersion', u'{version_str}')])
    ]),
    VarFileInfo([VarStruct(u'Translation', [0x0409, 1200])])
  ]
)
"""

Path("version_info.txt").write_text(content, encoding="utf-8")
print(f"version_info.txt written for v{version_str}")
