#!/usr/bin/python3
#---------------------write-tags-from-csv.py-------------------------------
# This code writes HSTL IPTC tags to all TIFF files listed in a CSV file
# generated by HST PDB.  
# The first row of the downloaded CSV [headers] must be edited to
# match the IPTC labels used below.  e.g Credit, By-line, SpecialInstructions,
# Objectname, Writer-Editor, Source, Headline and Caption-Abstract.
# 
#
# Created Sat 17 Jun 2023 03:34:20 AM CDT by JAU
#----------------------------------------------------------------

import csv
import exiftool

input_file="OriginalTIFs.csv"

with open(input_file, newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:

        filename = f"{row['ObjectName']}.tif"
        print(filename)
        with exiftool.ExifTool() as et:
            et.execute(b"-Headline=" + row["Headline"].encode('utf-8'), filename.encode('utf-8'))
            et.execute(b"-Credit=" + row["Credit"].encode('utf-8'), filename.encode('utf-8'))
            et.execute(b"-By-line=" + row["By-line"].encode('utf-8'), filename.encode('utf-8'))
            et.execute(b"-SpecialInstructions=" + row["SpecialInstructions"].encode('utf-8'), filename.encode('utf-8'))
            et.execute(b"-ObjectName=" + row["ObjectName"].encode('utf-8'), filename.encode('utf-8'))
            et.execute(b"-Writer-Editor=" + row["Writer-Editor"].encode('utf-8'), filename.encode('utf-8'))
            et.execute(b"-Source=" + row["Source"].encode('utf-8'), filename.encode('utf-8'))
            et.execute(b"-Caption-Abstract=" + row["Caption-Abstract"].encode('utf-8'), filename.encode('utf-8'))

